## contents
1. Basic array creation
2. Array generation function
3. Random generation function
4. Array attributes
5. Array methods
6. Re-sizing and reshaping

---

In [1]:
import numpy as np

In [2]:
#homogenous py list to numpy array
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [3]:
# other way of achieving the same

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
# heterogenous py list to numpy arr
lst_1 = [1,2,3.0,4,5]
arr_1 = np.array(lst_1)

lst_2 = [1,2,3,4.0,'hello']
arr_2 = np.array(lst_2)

print(arr_1,'\n',arr_2)

[1. 2. 3. 4. 5.] 
 ['1' '2' '3' '4.0' 'hello']


In [9]:
arr_1


array([1., 2., 3., 4., 5.])

In [10]:
arr_2


array(['1', '2', '3', '4.0', 'hello'], dtype='<U32')

the dtype='<U32' means a string type