# Advance


In [13]:
import numpy as np

## Numpy operations

### Slicing

#### Simple Slicing

In [14]:
array = np.arange(1,19)
print("Original array: ",array)
print("Sliced array: ",array[2:18])

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Sliced array:  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#### Slicing with steps

In [15]:
print("Steps sliced array: ", array[2:18:2])

Steps sliced array:  [ 3  5  7  9 11 13 15 17]


## 2D array operations

In [16]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Specific element

In [17]:
print("Specific element: ", matrix[1,2])

Specific element:  6


### Specific row 

In [18]:
print("specific row: ", matrix[1])

specific row:  [4 5 6]


### Specific column

In [19]:
print("specific column: ", matrix[:,2])

specific column:  [3 6 9]


## Array sorting

In [25]:
one_d_array = np.array([1,4,1,2,5])
two_d_array = np.array([[8,2,3],[5,5,1],[2,1,6]])
three_d_array = np.array([[[8,2,3],[5,5,1],[2,1,6]],[[8,2,3],[5,5,1],[2,1,6]]])
print(one_d_array)
print(two_d_array)
print(three_d_array)

[1 4 1 2 5]
[[8 2 3]
 [5 5 1]
 [2 1 6]]
[[[8 2 3]
  [5 5 1]
  [2 1 6]]

 [[8 2 3]
  [5 5 1]
  [2 1 6]]]


### 1D array sorting

In [22]:
sorted_1d_array = np.sort(one_d_array)
print(sorted_1d_array)

[1 1 2 4 5]


### 2D array sorting

In [23]:
sorted_2d_array = np.sort(two_d_array, axis=0)
print(sorted_2d_array)


[[2 1 1]
 [5 2 3]
 [8 5 6]]


In [28]:
sorted_3d_array = np.sort(three_d_array, axis=0)
print(sorted_3d_array)

[[[8 2 3]
  [5 5 1]
  [2 1 6]]

 [[8 2 3]
  [5 5 1]
  [2 1 6]]]
