# Advance


In [20]:
import numpy as np

## Numpy operations

### Slicing

#### Simple Slicing

In [21]:
array = np.arange(1,19)
print("Original array: ",array)
print("Sliced array: ",array[2:18])

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Sliced array:  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#### Slicing with steps

In [22]:
print("Steps sliced array: ", array[2:18:2])

Steps sliced array:  [ 3  5  7  9 11 13 15 17]


## 2D array operations

In [23]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Specific element

In [24]:
print("Specific element: ", matrix[1,2])

Specific element:  6


### Specific row 

In [25]:
print("specific row: ", matrix[1])

specific row:  [4 5 6]


### Specific column

In [26]:
print("specific column: ", matrix[:,2])

specific column:  [3 6 9]


## Array sorting

In [27]:
one_d_array = np.array([1,4,1,2,5])
two_d_array = np.array([[8,2,3],[5,5,1],[2,1,6]])
three_d_array = np.array([[[8,2,3],[5,5,1],[2,1,6]],[[8,2,3],[5,5,1],[2,1,6]]])
print(one_d_array)
print(two_d_array)
print(three_d_array)

[1 4 1 2 5]
[[8 2 3]
 [5 5 1]
 [2 1 6]]
[[[8 2 3]
  [5 5 1]
  [2 1 6]]

 [[8 2 3]
  [5 5 1]
  [2 1 6]]]


### 1D array sorting

In [28]:
sorted_1d_array = np.sort(one_d_array)
print(sorted_1d_array)

[1 1 2 4 5]


### 2D array sorting

In [29]:
sorted_2d_array = np.sort(two_d_array, axis=0)
print(sorted_2d_array)


[[2 1 1]
 [5 2 3]
 [8 5 6]]


In [30]:
sorted_3d_array = np.sort(three_d_array, axis=0)
print(sorted_3d_array)

[[[8 2 3]
  [5 5 1]
  [2 1 6]]

 [[8 2 3]
  [5 5 1]
  [2 1 6]]]


## Filtering

In [31]:
array = np.arange(1,21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Conditional Filtering

In [32]:
filtered_array = array[array > 10]
print(filtered_array)

[11 12 13 14 15 16 17 18 19 20]


### Filtering and replacement

In [33]:
filtered_replaced_array = np.where(array>5, array**2, array)
print(filtered_replaced_array)

[  1   2   3   4   5  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


## Array concatenation

**It is very important that the shape of the arrays are equal**

In [46]:
array_1 = np.array([[1,2,3,4],[5,6,7,8]])
array_2 = np.array([[10,20,30,40],[50,60,70,80]])

array_1_ = np.array([[100],[200]])


# checking if the shapes are equal
if array_1.shape == array_2.shape: print("Both arrays in equal shape...")
else: print("Shape unmatch detected...")

Both arrays in equal shape...


### Simple Array concatenation

In [40]:
simple_concatenated_array = np.concatenate((array_1, array_2))
print(simple_concatenated_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


### Row addition

In [42]:
row_add_array = np.vstack((array_1, array_2))
print(row_add_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


### column addition

In [47]:
col_add_array = np.hstack((array_1, array_1_))
print(col_add_array)

[[  1   2   3   4 100]
 [  5   6   7   8 200]]
