# Numpy array

Imports

In [2]:
import numpy as np
import time

## Creating array

In [3]:
array_1D = np.array([1,2,3])

array_2D = np.array([[1,2,3],[4,5,6]])

print("1D array : \n----\n",array_1D)
print("\n2D array : \n----\n",array_2D)

1D array : 
----
 [1 2 3]

2D array : 
----
 [[1 2 3]
 [4 5 6]]


## Difference between numpy and list

List -> duplication
Array -> Element-wise multiplication

In [4]:
list_1 = [1,2,3]

print("List multiplication:\n", list_1*3)

print("\nArray multiplication:\n", array_2D*3)

List multiplication:
 [1, 2, 3, 1, 2, 3, 1, 2, 3]

Array multiplication:
 [[ 3  6  9]
 [12 15 18]]


Difference in time of list-ops and array-ops

In [9]:
start_time_list = time.time()

list_container = [i*2 for i in range(100000000)]

print("The time : ", (time.time()-start_time_list)/60)

The time :  0.5327985485394796


In [12]:
start_time_array = time.time()

array_container = np.arange(100000000)

print("The time : ", (time.time()-start_time_array)/60)

The time :  0.06404219468434652


## Different ways of creating arrays

### With zeros

In [16]:
# takes tuple as input with row,col number
zero_array = np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### With ones

In [18]:
# takes tuple as input with row,col number
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### With Random numbers(0-1)

In [19]:
# takes tuple as input with row,col number
random_array = np.random.random((3,3))
print(random_array)


[[0.81056413 0.39164288 0.36082566]
 [0.50177386 0.73220141 0.92704644]
 [0.47354271 0.23925771 0.8273531 ]]


### With Range(sequence) of numbers


In [22]:
# takes as input, start,stop,step
range_array = np.arange(0,10,3)
print(range_array)

[0 3 6 9]


### With Constants

In [23]:
# takes tuple and contant as input ((row,col),constant)
constant_array = np.full((3,3),6)
print(constant_array)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


## Vector vs Matrix vs Tensor

### Vector

In [24]:
# takes list of numbers as input to convert in to array (should be of same data type)
vector = np.array([1,2,3])
print(vector)

[1 2 3]


### Matrix

In [25]:
# takes nested list of one level as input to convert in to array (should be of same data type)
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


### Tensor

In [ ]:
# n-dim array
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Properties of arrays

### Shape of array

In [27]:
print(tensor.shape)

(2, 2, 3)


### Dimension of array

In [28]:
print(tensor.ndim)

3


### Size of array

In [29]:
print(tensor.size)

12


### Dtype of array

In [30]:
print(tensor.dtype)

int64


## Common array operations

In [41]:
array = np.arange(1,19)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

### Reshaping

In [42]:
array_reshaped = array.reshape((3,6))
print(array_reshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


### Flattening

In [43]:
flattened_array = array_reshaped.flatten()
print(flattened_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### Ravel

In [44]:
Ravel_array = array_reshaped.ravel()
print(Ravel_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### Transposing

In [45]:
transpose_array = array_reshaped.T
print(transpose_array)

[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]
